---
- hosts: guest
  gather_facts: false
  vars:
    mount_on_boot: true
    vm_name: "{{ hostvars['variable_holder']['shared_variable'] }}"
  roles:
  - Hyperion/start and connect
  - VirtioFS/mount
