- hosts: host
  vars:
    vm_name: "ubuntu23.04"
  tasks:
  - set_fact:
      roles_path: "{{playbook_dir}}/roles"
  - add_host:
      name: "variable_holder"
      shared_variable:  "{{ vm_name }}"

# ToDo: Make this Smarter! and automatic.
#
# current limitations:
# - You have to start with the guest VM powered off.
# - you must run "ssh-copy-id user@guest"
# - and it must be added to hosts.

- name: Add virtio filesystem to vm
  ansible.builtin.import_playbook: play/host.yml

- name: Start and mount FS in guest
  ansible.builtin.import_playbook: play/guest.yml
  vars:
    share_folder: "/home/{{ansible_user}}/src"
