- hosts: host
  vars:
    vm_name: "ubuntu23.04"
  tasks:
  - set_fact:
      roles_path: "{{playbook_dir}}/roles"
  - add_host:
      name: "variable_holder"
      shared_variable:  "{{ vm_name }}"


- name: Add virtio filesystem to vm
  ansible.builtin.import_playbook: play/host.yml

- name: Start and mount FS in guest
  ansible.builtin.import_playbook: play/guest.yml
  vars:
    share_folder: "/home/{{ansible_user}}/src"
